# Generated by Django 4.0.4 on 2022-06-15 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_remove_profile_projects_profile_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('review', models.TextField(blank=True, max_length=3000)),
                ('stars', models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Try Again'), (3, '3 - Do Better'), (4, '4 - Not bad'), (5, '5 - OK'), (6, '6 - Mmmh'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Classical'), (10, '10 - Master Piece')])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
