# Generated by Django 4.0.4 on 2022-06-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_project_url_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - Poor'), (2, '2 - Try Again'), (3, '3 - Do Better'), (4, '4 - Not bad'), (5, '5 - OK'), (6, '6 - Mmmh'), (7, '7 - Good'), (8, '8 - Very Good'), (9, '9 - Classical'), (10, '10 - Master Piece')], default=0),
        ),
    ]
