# Generated by Django 4.0.4 on 2022-06-16 08:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rating_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='post image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='post image'),
        ),
    ]
