# Generated by Django 4.0.4 on 2022-06-22 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_project_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
